In [2]:
library(nycflights13)
library(tidyverse)

Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Registered S3 method overwritten by 'rvest':
  method            from
  read_xml.response xml2
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.1       ✔ purrr   0.3.2
✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
✔ tidyr   0.8.3       ✔ stringr 1.4.0
✔ readr   1.3.1       ✔ forcats 0.4.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
print(flights, n = 5, width = 500)

# A tibble: 336,776 x 19
   year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
  <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
1  2013     1     1      517            515         2      830            819
2  2013     1     1      533            529         4      850            830
3  2013     1     1      542            540         2      923            850
4  2013     1     1      544            545        -1     1004           1022
5  2013     1     1      554            600        -6      812            837
  arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
      <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
  time_hour
  <dttm>
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
# … with 3.368e+05 more rows

Warm-up
1. Create a dataframe containing just the carrier, flight, and tailnum of all flights flying to the Bay Area (SFO, OAK, or SJC).
2. Create a dataframe that excludes all flights from July 6th to August 7th (including those two dates).

In [5]:
# order rows by their departure time
print(arrange(flights, dep_time, month, day))

# A tibble: 336,776 x 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1    13        1           2249        72      108           2357
 2  2013     1    31        1           2100       181      124           2225
 3  2013     2    11        1           2100       181      111           2225
 4  2013     2    24        1           2245        76      121           2354
 5  2013     3     8        1           2355         6      431            440
 6  2013     3    18        1           2128       153      247           2355
 7  2013     3    19        1           2250        71      120              5
 8  2013     4     5        1           2359         2      410            339
 9  2013     4    10        1           1930       271      106           2101
10  2013     5    22        1           1935       266      154           2140
# … with 336,766 more rows, and 11 more variables: arr_delay <dbl>,
#   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
#   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>

In [6]:
# order rows by their arrival time (in descending order)
print(arrange(flights, desc(arr_time)))

# A tibble: 336,776 x 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1     2209           2155        14     2400           2337
 2  2013     1     5     2116           2130       -14     2400             18
 3  2013     1    13     2243           2129        74     2400           2224
 4  2013     1    16     2138           2107        31     2400           2322
 5  2013     1    17     2256           2249         7     2400           2357
 6  2013     1    22     2212           2055        77     2400           2250
 7  2013     1    22     2249           2125        84     2400           2250
 8  2013     1    25     2055           1725       210     2400           1933
 9  2013     1    28     2303           2250        13     2400           2354
10  2013     1    30     2155           1915       160     2400           2137
# … with 336,766 more rows, and 11 more variables: arr_delay <dbl>,
#   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
#   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>

In [9]:
# rename the dep_time column
print(rename(flights, "departure_time" = dep_time))

# A tibble: 336,776 x 19
    year month   day departure_time sched_dep_time dep_delay arr_time
   <int> <int> <int>          <int>          <int>     <dbl>    <int>
 1  2013     1     1            517            515         2      830
 2  2013     1     1            533            529         4      850
 3  2013     1     1            542            540         2      923
 4  2013     1     1            544            545        -1     1004
 5  2013     1     1            554            600        -6      812
 6  2013     1     1            554            558        -4      740
 7  2013     1     1            555            600        -5      913
 8  2013     1     1            557            600        -3      709
 9  2013     1     1            557            600        -3      838
10  2013     1     1            558            600        -2      753
# … with 336,766 more rows, and 12 more variables: sched_arr_time <int>,
#   arr_delay <dbl>, carrier <chr>, flight <int>, tailnum <chr>, origin <chr>,
#   dest <chr>, air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>,
#   time_hour <dttm>

We can create new variables/columns from existing columns!
- We can use arithmetic operators ```+```, ```-```, ```*```, ```/```, and ```^```.
- We can apply functions such as ```log()``` to a column.
- We can compare columns with comparison operators (```<```, ```==```, etc.)
- Everything is performed **element-wise**.

![col](https://raw.githubusercontent.com/mgruddy/Intro_Data_ScienceR_Spring2021/main/Slides/Screenshots/col_op.png)

In [11]:
# add the new variable air_time_hours
print(mutate(flights, air_time_hours = air_time / 60), width = 500)

# A tibble: 336,776 x 20
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
   arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
       <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
 1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
 2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
 3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
 4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
 5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
 6        12 UA        1696 N39463  EWR    ORD        150      719     5     58
 7        19 B6         507 N516JB  EWR    FLL        158     1065     6      0
 8       -14 EV        5708 N829AS  LGA    IAD         53      229     6      0
 9        -8 B6          79 N593JB  JFK    MCO        140      944     6      0
10         8 AA         301 N3ALAA  LGA    ORD        138      733     6      0
   time_hour           air_time_hours
   <dttm>                       <dbl>
 1 2013-01-01 05:00:00          3.78
 2 2013-01-01 05:00:00          3.78
 3 2013-01-01 05:00:00          2.67
 4 2013-01-01 05:00:00          3.05
 5 2013-01-01 06:00:00          1.93
 6 2013-01-01 05:00:00          2.5
 7 2013-01-01 06:00:00          2.63
 8 2013-01-01 06:00:00          0.883
 9 2013-01-01 06:00:00          2.33
10 2013-01-01 06:00:00          2.3
# … with 336,766 more rows

In [13]:
print(transmute(flights, air_time_hours = air_time / 60), width = 500)

# A tibble: 336,776 x 1
   air_time_hours
            <dbl>
 1          3.78
 2          3.78
 3          2.67
 4          3.05
 5          1.93
 6          2.5
 7          2.63
 8          0.883
 9          2.33
10          2.3
# … with 336,766 more rows

In [14]:
# new dataframe with only the new variables
print(transmute(flights, 
                air_time_hours = air_time / 60, 
                dist_km = distance * 1.6,
                avg_speed_mph = distance / air_time_hours))

# A tibble: 336,776 x 3
   air_time_hours dist_km avg_speed_mph
            <dbl>   <dbl>         <dbl>
 1          3.78    2240           370.
 2          3.78    2266.          374.
 3          2.67    1742.          408.
 4          3.05    2522.          517.
 5          1.93    1219.          394.
 6          2.5     1150.          288.
 7          2.63    1704           404.
 8          0.883    366.          259.
 9          2.33    1510.          405.
10          2.3     1173.          319.
# … with 336,766 more rows

In [17]:
print(mutate(flights,
                is_delayed = dep_time > sched_dep_time), width = 500)

# A tibble: 336,776 x 20
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
   arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
       <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
 1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
 2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
 3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
 4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
 5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
 6        12 UA        1696 N39463  EWR    ORD        150      719     5     58
 7        19 B6         507 N516JB  EWR    FLL        158     1065     6      0
 8       -14 EV        5708 N829AS  LGA    IAD         53      229     6      0
 9        -8 B6          79 N593JB  JFK    MCO        140      944     6      0
10         8 AA         301 N3ALAA  LGA    ORD        138      733     6      0
   time_hour           is_delayed
   <dttm>              <lgl>
 1 2013-01-01 05:00:00 TRUE
 2 2013-01-01 05:00:00 TRUE
 3 2013-01-01 05:00:00 TRUE
 4 2013-01-01 05:00:00 FALSE
 5 2013-01-01 06:00:00 FALSE
 6 2013-01-01 05:00:00 FALSE
 7 2013-01-01 06:00:00 FALSE
 8 2013-01-01 06:00:00 FALSE
 9 2013-01-01 06:00:00 FALSE
10 2013-01-01 06:00:00 FALSE
# … with 336,766 more rows

Attempt: Create a new dataset which has added a variable which is kilometers per hour of the flight.
- Bonus challenge. Make a dataset where this is the only variable

In [25]:
#print(mutate(flights, kil_per_hour = (1.6 * distance) / (air_time / 60)), width = 500)
flights_w_kph <- mutate(flights, dist_kil = 1.6 * distance,
                      air_time_hours = air_time / 60,
                      kil_per_hour = dist_kil / air_time_hours)
print(select(flights_w_kph, kil_per_hour))

# A tibble: 336,776 x 1
   kil_per_hour
          <dbl>
 1         592.
 2         599.
 3         653.
 4         827.
 5         631.
 6         460.
 7         647.
 8         415.
 9         647.
10         510.
# … with 336,766 more rows

Other column functions:
- ```mean(x)```: computes a number, the mean of column x
- ```sum(x)```: computes a number, the sum of a column x
- ```lead(x)```, ```lag(x)```: computes a new column, shifted down or up repsectively
- cumulative functions such as ```cumsum``` and ```cummean```: computes a new column, with the cumulative sum, mean, etc.
- ranking functions such as ```min_rank```: computes a new column, with the ranking of a column (2nd, 1st, etc.)

In [26]:
# adjust by the mean
print(transmute(flights,
                delay = dep_delay - mean(dep_delay)))

# A tibble: 336,776 x 1
   delay
   <dbl>
 1    NA
 2    NA
 3    NA
 4    NA
 5    NA
 6    NA
 7    NA
 8    NA
 9    NA
10    NA
# … with 336,766 more rows

In [27]:
# remove missing values
print(transmute(flights,
                delay = dep_delay - mean(dep_delay, na.rm = TRUE)))

# A tibble: 336,776 x 1
    delay
    <dbl>
 1 -10.6
 2  -8.64
 3 -10.6
 4 -13.6
 5 -18.6
 6 -16.6
 7 -17.6
 8 -15.6
 9 -15.6
10 -14.6
# … with 336,766 more rows

In [30]:
# rank the flights by the least delayed
print(mutate(flights,
                delay_rank = min_rank(dep_delay)), width = 500)

# A tibble: 336,776 x 20
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
   arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
       <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
 1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
 2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
 3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
 4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
 5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
 6        12 UA        1696 N39463  EWR    ORD        150      719     5     58
 7        19 B6         507 N516JB  EWR    FLL        158     1065     6      0
 8       -14 EV        5708 N829AS  LGA    IAD         53      229     6      0
 9        -8 B6          79 N593JB  JFK    MCO        140      944     6      0
10         8 AA         301 N3ALAA  LGA    ORD        138      733     6      0
   time_hour           delay_rank
   <dttm>                   <int>
 1 2013-01-01 05:00:00     208140
 2 2013-01-01 05:00:00     219823
 3 2013-01-01 05:00:00     208140
 4 2013-01-01 05:00:00     164763
 5 2013-01-01 06:00:00      48888
 6 2013-01-01 05:00:00      94410
 7 2013-01-01 06:00:00      69589
 8 2013-01-01 06:00:00     119029
 9 2013-01-01 06:00:00     119029
10 2013-01-01 06:00:00     143247
# … with 336,766 more rows

In [31]:
# rank the flights by the most delayed
print(mutate(flights,
                delay_rank = min_rank(desc(dep_delay))), width = 500)

# A tibble: 336,776 x 20
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
   arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
       <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
 1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
 2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
 3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
 4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
 5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
 6        12 UA        1696 N39463  EWR    ORD        150      719     5     58
 7        19 B6         507 N516JB  EWR    FLL        158     1065     6      0
 8       -14 EV        5708 N829AS  LGA    IAD         53      229     6      0
 9        -8 B6          79 N593JB  JFK    MCO        140      944     6      0
10         8 AA         301 N3ALAA  LGA    ORD        138      733     6      0
   time_hour           delay_rank
   <dttm>                   <int>
 1 2013-01-01 05:00:00     114150
 2 2013-01-01 05:00:00     103893
 3 2013-01-01 05:00:00     114150
 4 2013-01-01 05:00:00     144947
 5 2013-01-01 06:00:00     258934
 6 2013-01-01 05:00:00     209494
 7 2013-01-01 06:00:00     234113
 8 2013-01-01 06:00:00     185276
 9 2013-01-01 06:00:00     185276
10 2013-01-01 06:00:00     163760
# … with 336,766 more rows

To perform more than one operation on a dataset we can use the pipe, ```%>%```, to simplify our code.

Task: Create a dataset of the ten fastest flights.

In [32]:
flight_speeds <- mutate(flights, 
                            air_time_hours = air_time / 60, 
                            avg_speed_mph = distance / air_time_hours)

flight_speeds_ranked <- mutate(flight_speeds, avg_speed_rank = min_rank(desc(avg_speed_mph)))

(ten_fastest <- filter(flight_speeds_ranked, avg_speed_rank <= 10))

   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1  2013  1    12  1559     1600            -1       1849     1917
2  2013 11    16  2003     1925            38         17       36
3  2013 11    16  2349     2359           -10        402      440
4  2013 11    17   650      655            -5       1059     1150
5  2013 11    17   759      800            -1       1212     1255
6  2013 11    17   851      855            -4       1307     1345
7  2013 11    17  1926     1925             1          7       39
8  2013 12     5  1858     1900            -2       2313     2359
9  2013  2    10  1658     1700            -2       2125     2204
10 2013  2    10  1958     1855            63         31     2355
11 2013  2    21  2355     2358            -3        412      438
12 2013  3    23  1914     1910             4       2045     2043
13 2013  5    13  2040     2025            15       2225     2226
14 2013  5    25  1709     1700             9       1923     1937
15 2013  7     2  1558     1513            45       1745     1719
   arr_delay carrier ... origin dest air_time distance hour minute
1  -28       DL      ... LGA    PBI  105      1035     16    0
2  -19       DL      ... JFK    SJU  173      1598     19   25
3  -38       B6      ... JFK    SJU  173      1598     23   59
4  -51       DL      ... JFK    SJU  170      1598      6   55
5  -43       AA      ... JFK    STT  175      1623      8    0
6  -38       DL      ... JFK    SJU  173      1598      8   55
7  -32       DL      ... JFK    SJU  173      1598     19   25
8  -46       AA      ... JFK    SJU  173      1598     19    0
9  -39       DL      ... JFK    SJU  173      1598     17    0
10  36       AA      ... JFK    SJU  173      1598     18   55
11 -26       B6      ... JFK    SJU  172      1598     23   58
12   2       EV      ... EWR    BNA   70       748     19   10
13  -1       EV      ... EWR    GSP   55       594     20   25
14 -14       DL      ... LGA    ATL   65       762     17    0
15  26       EV      ... EWR    MSP   93      1008     15   13
   time_hour           air_time_hours avg_speed_mph avg_speed_rank
1  2013-01-12 16:00:00 1.7500000      591.4286      5
2  2013-11-16 19:00:00 2.8833333      554.2197      9
3  2013-11-16 23:00:00 2.8833333      554.2197      9
4  2013-11-17 06:00:00 2.8333333      564.0000      6
5  2013-11-17 08:00:00 2.9166667      556.4571      8
6  2013-11-17 08:00:00 2.8833333      554.2197      9
7  2013-11-17 19:00:00 2.8833333      554.2197      9
8  2013-12-05 19:00:00 2.8833333      554.2197      9
9  2013-02-10 17:00:00 2.8833333      554.2197      9
10 2013-02-10 18:00:00 2.8833333      554.2197      9
11 2013-02-21 23:00:00 2.8666667      557.4419      7
12 2013-03-23 19:00:00 1.1666667      641.1429      4
13 2013-05-13 20:00:00 0.9166667      648.0000      3
14 2013-05-25 17:00:00 1.0833333      703.3846      1
15 2013-07-02 15:00:00 1.5500000      650.3226      2

In [34]:
ten_fastest <- flights %>%
  mutate(air_time_hours = air_time / 60, avg_speed_mph = distance / air_time_hours) %>%
  mutate(avg_speed_rank = min_rank(desc(avg_speed_mph))) %>%
  filter(avg_speed_rank <= 10)

In [35]:
ten_fastest

   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1  2013  1    12  1559     1600            -1       1849     1917
2  2013 11    16  2003     1925            38         17       36
3  2013 11    16  2349     2359           -10        402      440
4  2013 11    17   650      655            -5       1059     1150
5  2013 11    17   759      800            -1       1212     1255
6  2013 11    17   851      855            -4       1307     1345
7  2013 11    17  1926     1925             1          7       39
8  2013 12     5  1858     1900            -2       2313     2359
9  2013  2    10  1658     1700            -2       2125     2204
10 2013  2    10  1958     1855            63         31     2355
11 2013  2    21  2355     2358            -3        412      438
12 2013  3    23  1914     1910             4       2045     2043
13 2013  5    13  2040     2025            15       2225     2226
14 2013  5    25  1709     1700             9       1923     1937
15 2013  7     2  1558     1513            45       1745     1719
   arr_delay carrier ... origin dest air_time distance hour minute
1  -28       DL      ... LGA    PBI  105      1035     16    0
2  -19       DL      ... JFK    SJU  173      1598     19   25
3  -38       B6      ... JFK    SJU  173      1598     23   59
4  -51       DL      ... JFK    SJU  170      1598      6   55
5  -43       AA      ... JFK    STT  175      1623      8    0
6  -38       DL      ... JFK    SJU  173      1598      8   55
7  -32       DL      ... JFK    SJU  173      1598     19   25
8  -46       AA      ... JFK    SJU  173      1598     19    0
9  -39       DL      ... JFK    SJU  173      1598     17    0
10  36       AA      ... JFK    SJU  173      1598     18   55
11 -26       B6      ... JFK    SJU  172      1598     23   58
12   2       EV      ... EWR    BNA   70       748     19   10
13  -1       EV      ... EWR    GSP   55       594     20   25
14 -14       DL      ... LGA    ATL   65       762     17    0
15  26       EV      ... EWR    MSP   93      1008     15   13
   time_hour           air_time_hours avg_speed_mph avg_speed_rank
1  2013-01-12 16:00:00 1.7500000      591.4286      5
2  2013-11-16 19:00:00 2.8833333      554.2197      9
3  2013-11-16 23:00:00 2.8833333      554.2197      9
4  2013-11-17 06:00:00 2.8333333      564.0000      6
5  2013-11-17 08:00:00 2.9166667      556.4571      8
6  2013-11-17 08:00:00 2.8833333      554.2197      9
7  2013-11-17 19:00:00 2.8833333      554.2197      9
8  2013-12-05 19:00:00 2.8833333      554.2197      9
9  2013-02-10 17:00:00 2.8833333      554.2197      9
10 2013-02-10 18:00:00 2.8833333      554.2197      9
11 2013-02-21 23:00:00 2.8666667      557.4419      7
12 2013-03-23 19:00:00 1.1666667      641.1429      4
13 2013-05-13 20:00:00 0.9166667      648.0000      3
14 2013-05-25 17:00:00 1.0833333      703.3846      1
15 2013-07-02 15:00:00 1.5500000      650.3226      2

Attempt: Using the ```msleep``` dataset, find the 5 omnivores which sleep the least amount of hours. Add a column for their total sleep in minutes. Do this in two ways, with and without the pipe command.


(Hint: Examine the ```vore``` and ```sleep_total``` columns)

Hint: try filtering then ranking then filtering.

In [3]:
msleep

    name                           genus         vore    order
1   Cheetah                        Acinonyx      carni   Carnivora
2   Owl monkey                     Aotus         omni    Primates
3   Mountain beaver                Aplodontia    herbi   Rodentia
4   Greater short-tailed shrew     Blarina       omni    Soricomorpha
5   Cow                            Bos           herbi   Artiodactyla
6   Three-toed sloth               Bradypus      herbi   Pilosa
7   Northern fur seal              Callorhinus   carni   Carnivora
8   Vesper mouse                   Calomys       NA      Rodentia
9   Dog                            Canis         carni   Carnivora
10  Roe deer                       Capreolus     herbi   Artiodactyla
11  Goat                           Capri         herbi   Artiodactyla
12  Guinea pig                     Cavis         herbi   Rodentia
13  Grivet                         Cercopithecus omni    Primates
14  Chinchilla                     Chinchilla    herbi   Rodentia
15  Star-nosed mole                Condylura     omni    Soricomorpha
16  African giant pouched rat      Cricetomys    omni    Rodentia
17  Lesser short-tailed shrew      Cryptotis     omni    Soricomorpha
18  Long-nosed armadillo           Dasypus       carni   Cingulata
19  Tree hyrax                     Dendrohyrax   herbi   Hyracoidea
20  North American Opossum         Didelphis     omni    Didelphimorphia
21  Asian elephant                 Elephas       herbi   Proboscidea
22  Big brown bat                  Eptesicus     insecti Chiroptera
23  Horse                          Equus         herbi   Perissodactyla
24  Donkey                         Equus         herbi   Perissodactyla
25  European hedgehog              Erinaceus     omni    Erinaceomorpha
26  Patas monkey                   Erythrocebus  omni    Primates
27  Western american chipmunk      Eutamias      herbi   Rodentia
28  Domestic cat                   Felis         carni   Carnivora
29  Galago                         Galago        omni    Primates
30  Giraffe                        Giraffa       herbi   Artiodactyla
... ...                            ...           ...     ...
54  Baboon                         Papio         omni    Primates
55  Desert hedgehog                Paraechinus   NA      Erinaceomorpha
56  Potto                          Perodicticus  omni    Primates
57  Deer mouse                     Peromyscus    NA      Rodentia
58  Phalanger                      Phalanger     NA      Diprotodontia
59  Caspian seal                   Phoca         carni   Carnivora
60  Common porpoise                Phocoena      carni   Cetacea
61  Potoroo                        Potorous      herbi   Diprotodontia
62  Giant armadillo                Priodontes    insecti Cingulata
63  Rock hyrax                     Procavia      NA      Hyracoidea
64  Laboratory rat                 Rattus        herbi   Rodentia
65  African striped mouse          Rhabdomys     omni    Rodentia
66  Squirrel monkey                Saimiri       omni    Primates
67  Eastern american mole          Scalopus      insecti Soricomorpha
68  Cotton rat                     Sigmodon      herbi   Rodentia
69  Mole rat                       Spalax        NA      Rodentia
70  Arctic ground squirrel         Spermophilus  herbi   Rodentia
71  Thirteen-lined ground squirrel Spermophilus  herbi   Rodentia
72  Golden-mantled ground squirrel Spermophilus  herbi   Rodentia
73  Musk shrew                     Suncus        NA      Soricomorpha
74  Pig                            Sus           omni    Artiodactyla
75  Short-nosed echidna            Tachyglossus  insecti Monotremata
76  Eastern american chipmunk      Tamias        herbi   Rodentia
77  Brazilian tapir                Tapirus       herbi   Perissodactyla
78  Tenrec                         Tenrec        omni    Afrosoricida
79  Tree shrew                     Tupaia        omni    Scandentia
80  Bottle-nosed dolphin           Tursiops      carni   Cetacea
81  Genet                          Genetta       carni   Carnivora
82  Arctic fox                     Vulpes        carni   Carnivora
83  Red fox                        Vulpes        carni   Carnivora
    conservation sleep_total sleep_rem sleep_cycle awake brainwt bodywt
1   lc           12.1         NA              NA   11.9       NA   50.000
2   NA           17.0        1.8              NA    7.0  0.01550    0.480
3   nt           14.4        2.4              NA    9.6       NA    1.350
4   lc           14.9        2.3       0.1333333    9.1  0.00029    0.019
5   domesticated  4.0        0.7       0.6666667   20.0  0.42300  600.000
6   NA           14.4        2.2       0.7666667    9.6       NA    3.850
7   vu            8.7        1.4       0.3833333   15.3       NA   20.490
8   NA            7.0         NA              NA   17.0       NA    0.045
9   domesticated 10.1        2.9       0.3333333   13.9  0.07000   14.000
10  lc            3.0         NA              NA   21.0  0.09820   14.800
11  lc            5.3        0.6              NA   18.7  0.11500   33.500
12  domesticated  9.4        0.8       0.2166667   14.6  0.00550    0.728
13  lc           10.0        0.7              NA   14.0       NA    4.750
14  domesticated 12.5        1.5       0.1166667   11.5  0.00640    0.420
15  lc           10.3        2.2              NA   13.7  0.00100    0.060
16  NA            8.3        2.0              NA   15.7  0.00660    1.000
17  lc            9.1        1.4       0.1500000   14.9  0.00014    0.005
18  lc           17.4        3.1       0.3833333    6.6  0.01080    3.500
19  lc            5.3        0.5              NA   18.7  0.01230    2.950
20  lc           18.0        4.9       0.3333333    6.0  0.00630    1.700
21  en            3.9         NA              NA   20.1  4.60300 2547.000
22  lc           19.7        3.9       0.1166667    4.3  0.00030    0.023
23  domesticated  2.9        0.6       1.0000000   21.1  0.65500  521.000
24  domesticated  3.1        0.4              NA   20.9  0.41900  187.000
25  lc           10.1        3.5       0.2833333   13.9  0.00350    0.770
26  lc           10.9        1.1              NA   13.1  0.11500   10.000
27  NA           14.9         NA              NA    9.1       NA    0.071
28  domesticated 12.5        3.2       0.4166667   11.5  0.02560    3.300
29  NA            9.8        1.1       0.5500000   14.2  0.00500    0.200
30  cd            1.9        0.4              NA   22.1       NA  899.995
... ...          ...         ...       ...         ...   ...     ...
54  NA            9.4        1.0       0.6666667   14.60 0.18000  25.235
55  lc           10.3        2.7              NA   13.70 0.00240   0.550
56  lc           11.0         NA              NA   13.00      NA   1.100
57  NA           11.5         NA              NA   12.50      NA   0.021
58  NA           13.7        1.8              NA   10.30 0.01140   1.620
59  vu            3.5        0.4              NA   20.50      NA  86.000
60  vu            5.6         NA              NA   18.45      NA  53.180
61  NA           11.1        1.5              NA   12.90      NA   1.100
62  en           18.1        6.1              NA    5.90 0.08100  60.000
63  lc            5.4        0.5              NA   18.60 0.02100   3.600
64  lc           13.0        2.4       0.1833333   11.00 0.00190   0.320
65  NA            8.7         NA              NA   15.30      NA   0.044
66  NA            9.6        1.4              NA   14.40 0.02000   0.743
67  lc            8.4        2.1       0.1666667   15.60 0.00120   0.075
68  NA           11.3        1.1       0.1500000   12.70 0.00118   0.148
69  NA           10.6        2.4              NA   13.40 0.00300   0.122
70  lc           16.6         NA              NA    7.40 0.00570   0.920
71  lc           13.8        3.4       0.2166667   10.20 0.00400   0.101
72  lc           15.9        3.0              NA    8.10      NA   0.205
73  NA           12.8        2.0       0.1833333   11.20 0.00033   0.048
74  domesticated  9.1        2.4       0.5000000   14.90 0.18000  86.250
75  NA            8.6         NA              NA   15.40 0.02500   4.500
76  NA           15.8         NA              NA    8.20      NA   0.112
77  vu            4.4        1.0       0.9000000   19.60 0.16900 207.501
78  NA           15.6        2.3              NA    8.40 0.00260   0.900
79  NA            8.9        2.6       0.2333333   15.10 0.00250   0.104
80  NA            5.2         NA              NA   18.80      NA 173.330
81  NA            6.3        1.3              NA   17.70 0.01750   2.000
82  NA           12.5         NA              NA   11.50 0.04450   3.380
83  NA            9.8        2.4       0.3500000   14.20 0.05040   4.230

In [4]:
msleep_omni <- filter(msleep, vore == "omni")

In [5]:
msleep_omni_ranked <- mutate(msleep_omni, sleep_rank = min_rank(sleep_total))

In [6]:
(msleep_10_least <- filter(msleep_omni_ranked, sleep_rank <= 10))

   name                      genus      vore order        conservation
1  African giant pouched rat Cricetomys omni Rodentia     NA
2  Lesser short-tailed shrew Cryptotis  omni Soricomorpha lc
3  Galago                    Galago     omni Primates     NA
4  Human                     Homo       omni Primates     NA
5  Chimpanzee                Pan        omni Primates     NA
6  Baboon                    Papio      omni Primates     NA
7  African striped mouse     Rhabdomys  omni Rodentia     NA
8  Squirrel monkey           Saimiri    omni Primates     NA
9  Pig                       Sus        omni Artiodactyla domesticated
10 Tree shrew                Tupaia     omni Scandentia   NA
   sleep_total sleep_rem sleep_cycle awake brainwt bodywt sleep_rank
1  8.3         2.0              NA   15.7  0.00660  1.000  2
2  9.1         1.4       0.1500000   14.9  0.00014  0.005  5
3  9.8         1.1       0.5500000   14.2  0.00500  0.200 10
4  8.0         1.9       1.5000000   16.0  1.32000 62.000  1
5  9.7         1.4       1.4166667   14.3  0.44000 52.200  9
6  9.4         1.0       0.6666667   14.6  0.18000 25.235  7
7  8.7          NA              NA   15.3       NA  0.044  3
8  9.6         1.4              NA   14.4  0.02000  0.743  8
9  9.1         2.4       0.5000000   14.9  0.18000 86.250  5
10 8.9         2.6       0.2333333   15.1  0.00250  0.104  4

In [7]:
msleep_10_least_omni <- msleep %>%
  filter(vore == "omni") %>%
  mutate(sleep_rank = min_rank(sleep_total)) %>%
  filter(sleep_rank <= 10)

In [8]:
msleep_10_least_omni

   name                      genus      vore order        conservation
1  African giant pouched rat Cricetomys omni Rodentia     NA
2  Lesser short-tailed shrew Cryptotis  omni Soricomorpha lc
3  Galago                    Galago     omni Primates     NA
4  Human                     Homo       omni Primates     NA
5  Chimpanzee                Pan        omni Primates     NA
6  Baboon                    Papio      omni Primates     NA
7  African striped mouse     Rhabdomys  omni Rodentia     NA
8  Squirrel monkey           Saimiri    omni Primates     NA
9  Pig                       Sus        omni Artiodactyla domesticated
10 Tree shrew                Tupaia     omni Scandentia   NA
   sleep_total sleep_rem sleep_cycle awake brainwt bodywt sleep_rank
1  8.3         2.0              NA   15.7  0.00660  1.000  2
2  9.1         1.4       0.1500000   14.9  0.00014  0.005  5
3  9.8         1.1       0.5500000   14.2  0.00500  0.200 10
4  8.0         1.9       1.5000000   16.0  1.32000 62.000  1
5  9.7         1.4       1.4166667   14.3  0.44000 52.200  9
6  9.4         1.0       0.6666667   14.6  0.18000 25.235  7
7  8.7          NA              NA   15.3       NA  0.044  3
8  9.6         1.4              NA   14.4  0.02000  0.743  8
9  9.1         2.4       0.5000000   14.9  0.18000 86.250  5
10 8.9         2.6       0.2333333   15.1  0.00250  0.104  4