In [1]:
library(tidyverse)
library(nycflights13)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.0.6     ✔ dplyr   1.0.4
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
# US panda births
(us_born_pandas = read_csv("data/us_born_pandas.csv"))

# Current pandas in the United States
(us_current_pandas = read_csv("data/us_current_pandas.csv"))

── Column specification ────────────────────────────────────────────────────────
cols(
  name = col_character(),
  birth_date = col_character(),
  birth_location = col_character()
)

   name       birth_date birth_location
1  Hua Mei    8/21/99    San Diego Zoo
2  Mei Sheng  8/19/03    San Diego Zoo
3  Su Lin     8/2/05     San Diego Zoo
4  Yun Zi     8/5/09     San Diego Zoo
5  Zhen Zhen  8/3/07     San Diego Zoo
6  Xiao Liwu  7/29/12    San Diego Zoo
7  Mei Lan    9/6/06     Atlanta Zoo
8  Xi Lan     8/30/08    Atlanta Zoo
9  Po         10/3/10    Atlanta Zoo
10 Mei Lun    7/15/13    Atlanta Zoo
11 Mei Huan   7/15/13    Atlanta Zoo
12 Tai Shan   7/9/05     Smithsonian National Zoo
13 Bao Bao    8/23/13    Smithsonian National Zoo
14 Bei Bei    8/22/15    Smithsonian National Zoo
15 Xiao Qi Ji 8/21/20    Smithsonian National Zoo

── Column specification ────────────────────────────────────────────────────────
cols(
  name = col_character(),
  location = col_character(),
  sex = col_character()
)

  name       location                 sex
1 Le Le      Memphis Zoo              male
2 Ya Ya      Memphis Zoo              female
3 Lun Lun    Atlanta Zoo              female
4 Mei Lan    Atlanta Zoo              male
5 Yang Yang  Atlanta Zoo              male
6 Tian Tian  Smithsonian National Zoo male
7 Mei Xiang  Smithsonian National Zoo female
8 Xiao Qi Ji Smithsonian National Zoo male

### Outer Joins

Missing values are inserted when keys are missing

![](https://d33wubrfki0l68.cloudfront.net/9c12ca9e12ed26a7c5d2aa08e36d2ac4fb593f1e/79980/diagrams/join-outer.png)

- Left/Right join: all observations from the left/right dataset are preserved. Missing values are inserted when the key value in the left/right dataset does not appear in the other dataset
- Full join: all observations are preserved. Missing values are inserted whenever a key value does not appear in one of the datasets

Attempt:
- Perform an inner, left, right, and full join for the two datasets ```us_born_pandas``` and ```us_current_pandas``` (treating the former as the "left" dataset and the latter as the "right" dataset)
- Count the rows in all **six** datasets. What do you notice?

In [6]:
inner_join(us_born_pandas, us_current_pandas, by = "name")

  name       birth_date birth_location           location                 sex
1 Mei Lan    9/6/06     Atlanta Zoo              Atlanta Zoo              male
2 Xiao Qi Ji 8/21/20    Smithsonian National Zoo Smithsonian National Zoo male

In [8]:
left_join(us_born_pandas, us_current_pandas, by = "name")

   name       birth_date birth_location           location                 sex
1  Hua Mei    8/21/99    San Diego Zoo            NA                       NA
2  Mei Sheng  8/19/03    San Diego Zoo            NA                       NA
3  Su Lin     8/2/05     San Diego Zoo            NA                       NA
4  Yun Zi     8/5/09     San Diego Zoo            NA                       NA
5  Zhen Zhen  8/3/07     San Diego Zoo            NA                       NA
6  Xiao Liwu  7/29/12    San Diego Zoo            NA                       NA
7  Mei Lan    9/6/06     Atlanta Zoo              Atlanta Zoo              male
8  Xi Lan     8/30/08    Atlanta Zoo              NA                       NA
9  Po         10/3/10    Atlanta Zoo              NA                       NA
10 Mei Lun    7/15/13    Atlanta Zoo              NA                       NA
11 Mei Huan   7/15/13    Atlanta Zoo              NA                       NA
12 Tai Shan   7/9/05     Smithsonian National Zoo NA                       NA
13 Bao Bao    8/23/13    Smithsonian National Zoo NA                       NA
14 Bei Bei    8/22/15    Smithsonian National Zoo NA                       NA
15 Xiao Qi Ji 8/21/20    Smithsonian National Zoo Smithsonian National Zoo male

In [9]:
right_join(us_born_pandas, us_current_pandas, by = "name")

  name       birth_date birth_location           location
1 Mei Lan    9/6/06     Atlanta Zoo              Atlanta Zoo
2 Xiao Qi Ji 8/21/20    Smithsonian National Zoo Smithsonian National Zoo
3 Le Le      NA         NA                       Memphis Zoo
4 Ya Ya      NA         NA                       Memphis Zoo
5 Lun Lun    NA         NA                       Atlanta Zoo
6 Yang Yang  NA         NA                       Atlanta Zoo
7 Tian Tian  NA         NA                       Smithsonian National Zoo
8 Mei Xiang  NA         NA                       Smithsonian National Zoo
  sex
1 male
2 male
3 male
4 female
5 female
6 male
7 male
8 female

In [10]:
full_join(us_born_pandas, us_current_pandas, by = "name")

   name       birth_date birth_location           location
1  Hua Mei    8/21/99    San Diego Zoo            NA
2  Mei Sheng  8/19/03    San Diego Zoo            NA
3  Su Lin     8/2/05     San Diego Zoo            NA
4  Yun Zi     8/5/09     San Diego Zoo            NA
5  Zhen Zhen  8/3/07     San Diego Zoo            NA
6  Xiao Liwu  7/29/12    San Diego Zoo            NA
7  Mei Lan    9/6/06     Atlanta Zoo              Atlanta Zoo
8  Xi Lan     8/30/08    Atlanta Zoo              NA
9  Po         10/3/10    Atlanta Zoo              NA
10 Mei Lun    7/15/13    Atlanta Zoo              NA
11 Mei Huan   7/15/13    Atlanta Zoo              NA
12 Tai Shan   7/9/05     Smithsonian National Zoo NA
13 Bao Bao    8/23/13    Smithsonian National Zoo NA
14 Bei Bei    8/22/15    Smithsonian National Zoo NA
15 Xiao Qi Ji 8/21/20    Smithsonian National Zoo Smithsonian National Zoo
16 Le Le      NA         NA                       Memphis Zoo
17 Ya Ya      NA         NA                       Memphis Zoo
18 Lun Lun    NA         NA                       Atlanta Zoo
19 Yang Yang  NA         NA                       Atlanta Zoo
20 Tian Tian  NA         NA                       Smithsonian National Zoo
21 Mei Xiang  NA         NA                       Smithsonian National Zoo
   sex
1  NA
2  NA
3  NA
4  NA
5  NA
6  NA
7  male
8  NA
9  NA
10 NA
11 NA
12 NA
13 NA
14 NA
15 male
16 male
17 female
18 female
19 male
20 male
21 female

```left_join(df1, df2)``` is the same as ```right_join(df2, df1)```

### Duplicate Keys
![](https://d33wubrfki0l68.cloudfront.net/6faac3e996263827cb57fc5803df6192541a9a4b/c7d74/diagrams/join-one-to-many.png)

In [11]:
# let's add the airline name to the flights dataset
airlines

   carrier name
1  9E      Endeavor Air Inc.
2  AA      American Airlines Inc.
3  AS      Alaska Airlines Inc.
4  B6      JetBlue Airways
5  DL      Delta Air Lines Inc.
6  EV      ExpressJet Airlines Inc.
7  F9      Frontier Airlines Inc.
8  FL      AirTran Airways Corporation
9  HA      Hawaiian Airlines Inc.
10 MQ      Envoy Air
11 OO      SkyWest Airlines Inc.
12 UA      United Air Lines Inc.
13 US      US Airways Inc.
14 VX      Virgin America
15 WN      Southwest Airlines Co.
16 YV      Mesa Airlines Inc.

In [14]:
# left join is useful when we have a "main" dataset that we'd like to add variables to
left_join(flights, airlines, by = "carrier") %>%
    rename("carrier_name" = "name") %>%
    select(year:carrier, carrier_name, flight:time_hour)

#select(carrier_name, everything())

       carrier_name             year month day dep_time sched_dep_time
1      United Air Lines Inc.    2013 1     1   517      515
2      United Air Lines Inc.    2013 1     1   533      529
3      American Airlines Inc.   2013 1     1   542      540
4      JetBlue Airways          2013 1     1   544      545
5      Delta Air Lines Inc.     2013 1     1   554      600
6      United Air Lines Inc.    2013 1     1   554      558
7      JetBlue Airways          2013 1     1   555      600
8      ExpressJet Airlines Inc. 2013 1     1   557      600
9      JetBlue Airways          2013 1     1   557      600
10     American Airlines Inc.   2013 1     1   558      600
11     JetBlue Airways          2013 1     1   558      600
12     JetBlue Airways          2013 1     1   558      600
13     United Air Lines Inc.    2013 1     1   558      600
14     United Air Lines Inc.    2013 1     1   558      600
15     American Airlines Inc.   2013 1     1   559      600
16     JetBlue Airways          2013 1     1   559      559
17     United Air Lines Inc.    2013 1     1   559      600
18     JetBlue Airways          2013 1     1   600      600
19     Envoy Air                2013 1     1   600      600
20     JetBlue Airways          2013 1     1   601      600
21     Delta Air Lines Inc.     2013 1     1   602      610
22     Envoy Air                2013 1     1   602      605
23     American Airlines Inc.   2013 1     1   606      610
24     Delta Air Lines Inc.     2013 1     1   606      610
25     United Air Lines Inc.    2013 1     1   607      607
26     Envoy Air                2013 1     1   608      600
27     United Air Lines Inc.    2013 1     1   611      600
28     JetBlue Airways          2013 1     1   613      610
29     JetBlue Airways          2013 1     1   615      615
30     Delta Air Lines Inc.     2013 1     1   615      615
⋮      ⋮                        ⋮    ⋮     ⋮   ⋮        ⋮
336747 ExpressJet Airlines Inc. 2013 9     30  2123     2125
336748 ExpressJet Airlines Inc. 2013 9     30  2127     2129
336749 JetBlue Airways          2013 9     30  2128     2130
336750 ExpressJet Airlines Inc. 2013 9     30  2129     2059
336751 Envoy Air                2013 9     30  2131     2140
336752 American Airlines Inc.   2013 9     30  2140     2140
336753 ExpressJet Airlines Inc. 2013 9     30  2142     2129
336754 JetBlue Airways          2013 9     30  2145     2145
336755 JetBlue Airways          2013 9     30  2147     2137
336756 United Air Lines Inc.    2013 9     30  2149     2156
336757 ExpressJet Airlines Inc. 2013 9     30  2150     2159
336758 Endeavor Air Inc.        2013 9     30  2159     1845
336759 ExpressJet Airlines Inc. 2013 9     30  2203     2205
336760 Envoy Air                2013 9     30  2207     2140
336761 ExpressJet Airlines Inc. 2013 9     30  2211     2059
336762 JetBlue Airways          2013 9     30  2231     2245
336763 United Air Lines Inc.    2013 9     30  2233     2113
336764 JetBlue Airways          2013 9     30  2235     2001
336765 JetBlue Airways          2013 9     30  2237     2245
336766 JetBlue Airways          2013 9     30  2240     2245
336767 JetBlue Airways          2013 9     30  2240     2250
336768 JetBlue Airways          2013 9     30  2241     2246
336769 JetBlue Airways          2013 9     30  2307     2255
336770 JetBlue Airways          2013 9     30  2349     2359
336771 ExpressJet Airlines Inc. 2013 9     30    NA     1842
336772 Endeavor Air Inc.        2013 9     30    NA     1455
336773 Endeavor Air Inc.        2013 9     30    NA     2200
336774 Envoy Air                2013 9     30    NA     1210
336775 Envoy Air                2013 9     30    NA     1159
336776 Envoy Air                2013 9     30    NA      840
       dep_delay arr_time sched_arr_time arr_delay carrier flight tailnum
1       2         830      819            11       UA      1545   N14228
2       4         850      830            20       UA      1714   N24211
3       2         923      850            33       AA      1141   N619AA
4      -1        1004     1022           -18       B6       725   N804JB
5      -6         812      837           -25       DL       461   N668DN
6      -4         740      728            12       UA      1696   N39463
7      -5         913      854            19       B6       507   N516JB
8      -3         709      723           -14       EV      5708   N829AS
9      -3         838      846            -8       B6        79   N593JB
10     -2         753      745             8       AA       301   N3ALAA
11     -2         849      851            -2       B6        49   N793JB
12     -2         853      856            -3       B6        71   N657JB
13     -2         924      917             7       UA       194   N29129
14     -2         923      937           -14       UA      1124   N53441
15     -1         941      910            31       AA       707   N3DUAA
16      0         702      706            -4       B6      1806   N708JB
17     -1         854      902            -8       UA      1187   N76515
18      0         851      858            -7       B6       371   N595JB
19      0         837      825            12       MQ      4650   N542MQ
20      1         844      850            -6       B6       343   N644JB
21     -8         812      820            -8       DL      1919   N971DL
22     -3         821      805            16       MQ      4401   N730MQ
23     -4         858      910           -12       AA      1895   N633AA
24     -4         837      845            -8       DL      1743   N3739P
25      0         858      915           -17       UA      1077   N53442
26      8         807      735            32       MQ      3768   N9EAMQ
27     11         945      931            14       UA       303   N532UA
28      3         925      921             4       B6       135   N635JB
29      0        1039     1100           -21       B6       709   N794JB
30      0         833      842            -9       DL       575   N326NB
⋮      ⋮         ⋮        ⋮              ⋮         ⋮       ⋮      ⋮
336747  -2       2223     2247           -24       EV      5489   N712EV
336748  -2       2314     2323            -9       EV      3833   N16546
336749  -2       2328     2359           -31       B6        97   N807JB
336750  30       2230     2232            -2       EV      5048   N751EV
336751  -9       2225     2255           -30       MQ      3621   N807MQ
336752   0         10       40           -30       AA       185   N335AA
336753  13       2250     2239            11       EV      4509   N12957
336754   0        115      140           -25       B6      1103   N633JB
336755  10         30       27             3       B6      1371   N627JB
336756  -7       2245     2308           -23       UA       523   N813UA
336757  -9       2250     2306           -16       EV      3842   N10575
336758 194       2344     2030           194       9E      3320   N906XJ
336759  -2       2339     2331             8       EV      5311   N722EV
336760  27       2257     2250             7       MQ      3660   N532MQ
336761  72       2339     2242            57       EV      4672   N12145
336762 -14       2335     2356           -21       B6       108   N193JB
336763  80        112       30            42       UA       471   N578UA
336764 154         59     2249           130       B6      1083   N804JB
336765  -8       2345     2353            -8       B6       234   N318JB
336766  -5       2334     2351           -17       B6      1816   N354JB
336767 -10       2347        7           -20       B6      2002   N281JB
336768  -5       2345        1           -16       B6       486   N346JB
336769  12       2359     2358             1       B6       718   N565JB
336770 -10        325      350           -25       B6       745   N516JB
336771  NA         NA     2019            NA       EV      5274   N740EV
336772  NA         NA     1634            NA       9E      3393   NA
336773  NA         NA     2312            NA       9E      3525   NA
336774  NA         NA     1330            NA       MQ      3461   N535MQ
336775  NA         NA     1344            NA       MQ      3572   N511MQ
336776  NA         NA     1020            NA       MQ      3531   N839MQ
       origin dest air_time distance hour minute time_hour
1      EWR    IAH  227      1400     5    15     2013-01-01 05:00:00
2      LGA    IAH  227      1416     5    29     2013-01-01 05:00:00
3      JFK    MIA  160      1089     5    40     2013-01-01 05:00:00
4      JFK    BQN  183      1576     5    45     2013-01-01 05:00:00
5      LGA    ATL  116       762     6     0     2013-01-01 06:00:00
6      EWR    ORD  150       719     5    58     2013-01-01 05:00:00
7      EWR    FLL  158      1065     6     0     2013-01-01 06:00:00
8      LGA    IAD   53       229     6     0     2013-01-01 06:00:00
9      JFK    MCO  140       944     6     0     2013-01-01 06:00:00
10     LGA    ORD  138       733     6     0     2013-01-01 06:00:00
11     JFK    PBI  149      1028     6     0     2013-01-01 06:00:00
12     JFK    TPA  158      1005     6     0     2013-01-01 06:00:00
13     JFK    LAX  345      2475     6     0     2013-01-01 06:00:00
14     EWR    SFO  361      2565     6     0     2013-01-01 06:00:00
15     LGA    DFW  257      1389     6     0     2013-01-01 06:00:00
16     JFK    BOS   44       187     5    59     2013-01-01 05:00:00
17     EWR    LAS  337      2227     6     0     2013-01-01 06:00:00
18     LGA    FLL  152      1076     6     0     2013-01-01 06:00:00
19     LGA    ATL  134       762     6     0     2013-01-01 06:00:00
20     EWR    PBI  147      1023     6     0     2013-01-01 06:00:00
21     LGA    MSP  170      1020     6    10     2013-01-01 06:00:00
22     LGA    DTW  105       502     6     5     2013-01-01 06:00:00
23     EWR    MIA  152      1085     6    10     2013-01-01 06:00:00
24     JFK    ATL  128       760     6    10     2013-01-01 06:00:00
25     EWR    MIA  157      1085     6     7     2013-01-01 06:00:00
26     EWR    ORD  139       719     6     0     2013-01-01 06:00:00
27     JFK    SFO  366      2586     6     0     2013-01-01 06:00:00
28     JFK    RSW  175      1074     6    10     2013-01-01 06:00:00
29     JFK    SJU  182      1598     6    15     2013-01-01 06:00:00
30     EWR    ATL  120       746     6    15     2013-01-01 06:00:00
⋮      ⋮      ⋮    ⋮        ⋮        ⋮    ⋮      ⋮
336747 LGA    CHO   45       305     21   25     2013-09-30 21:00:00
336748 EWR    CLT   72       529     21   29     2013-09-30 21:00:00
336749 JFK    DEN  213      1626     21   30     2013-09-30 21:00:00
336750 LGA    RIC   45       292     20   59     2013-09-30 20:00:00
336751 JFK    DCA   36       213     21   40     2013-09-30 21:00:00
336752 JFK    LAX  298      2475     21   40     2013-09-30 21:00:00
336753 EWR    PWM   47       284     21   29     2013-09-30 21:00:00
336754 JFK    SJU  192      1598     21   45     2013-09-30 21:00:00
336755 LGA    FLL  139      1076     21   37     2013-09-30 21:00:00
336756 EWR    BOS   37       200     21   56     2013-09-30 21:00:00
336757 EWR    MHT   39       209     21   59     2013-09-30 21:00:00
336758 JFK    BUF   50       301     18   45     2013-09-30 18:00:00
336759 LGA    BGR   61       378     22    5     2013-09-30 22:00:00
336760 LGA    BNA   97       764     21   40     2013-09-30 21:00:00
336761 EWR    STL  120       872     20   59     2013-09-30 20:00:00
336762 JFK    PWM   48       273     22   45     2013-09-30 22:00:00
336763 EWR    SFO  318      2565     21   13     2013-09-30 21:00:00
336764 JFK    MCO  123       944     20    1     2013-09-30 20:00:00
336765 JFK    BTV   43       266     22   45     2013-09-30 22:00:00
336766 JFK    SYR   41       209     22   45     2013-09-30 22:00:00
336767 JFK    BUF   52       301     22   50     2013-09-30 22:00:00
336768 JFK    ROC   47       264     22   46     2013-09-30 22:00:00
336769 JFK    BOS   33       187     22   55     2013-09-30 22:00:00
336770 JFK    PSE  196      1617     23   59     2013-09-30 23:00:00
336771 LGA    BNA   NA       764     18   42     2013-09-30 18:00:00
336772 JFK    DCA   NA       213     14   55     2013-09-30 14:00:00
336773 LGA    SYR   NA       198     22    0     2013-09-30 22:00:00
336774 LGA    BNA   NA       764     12   10     2013-09-30 12:00:00
336775 LGA    CLE   NA       419     11   59     2013-09-30 11:00:00
336776 LGA    RDU   NA       431      8   40     2013-09-30 08:00:00

Attempt:
- Try all three outer joins to join the ```weather``` and ```flights``` dataset
- Describe in words what observations will have missing values in **each** case.
- Which makes the most sense if you want to understand the effect of weather patterns on specific flights? What if you want to investigate a particular day of the year?

In [20]:
left_join(flights, weather, by = c("year", "month", "day", "hour", "origin")) %>%
    print(width = Inf)

# A tibble: 336,776 x 29
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
   arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
       <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
 1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
 2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
 3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
 4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
 5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
 6        12 UA        1696 N39463  EWR    ORD        150      719     5     58
 7        19 B6         507 N516JB  EWR    FLL        158     1065     6      0
 8       -14 EV        5708 N829AS  LGA    IAD         53      229     6      0
 9        -8 B6          79 N593JB  JFK    MCO        140      944     6      0
10         8 AA         301 N3ALAA  LGA    ORD        138      733     6      0
   time_hour.x          temp  dewp humid wind_dir wind_speed wind_gust precip
   <dttm>              <dbl> <dbl> <dbl>    <dbl>      <dbl>     <dbl>  <dbl>
 1 2013-01-01 05:00:00  39.0  28.0  64.4      260       12.7      NA        0
 2 2013-01-01 05:00:00  39.9  25.0  54.8      250       15.0      21.9      0
 3 2013-01-01 05:00:00  39.0  27.0  61.6      260       15.0      NA        0
 4 2013-01-01 05:00:00  39.0  27.0  61.6      260       15.0      NA        0
 5 2013-01-01 06:00:00  39.9  25.0  54.8      260       16.1      23.0      0
 6 2013-01-01 05:00:00  39.0  28.0  64.4      260       12.7      NA        0
 7 2013-01-01 06:00:00  37.9  28.0  67.2      240       11.5      NA        0
 8 2013-01-01 06:00:00  39.9  25.0  54.8      260       16.1      23.0      0
 9 2013-01-01 06:00:00  37.9  27.0  64.3      260       13.8      NA        0
10 2013-01-01 06:00:00  39.9  25.0  54.8      260       16.1      23.0      0
   pressure visib time_hour.y
      <dbl> <dbl> <dttm>
 1    1012.    10 2013-01-01 05:00:00
 2    1011.    10 2013-01-01 05:00:00
 3    1012.    10 2013-01-01 05:00:00
 4    1012.    10 2013-01-01 05:00:00
 5    1012.    10 2013-01-01 06:00:00
 6    1012.    10 2013-01-01 05:00:00
 7    1012.    10 2013-01-01 06:00:00
 8    1012.    10 2013-01-01 06:00:00
 9    1013.    10 2013-01-01 06:00:00
10    1012.    10 2013-01-01 06:00:00
# … with 336,766 more rows

### Semi-Join
![](https://d33wubrfki0l68.cloudfront.net/028065a7f353a932d70d2dfc82bc5c5966f768ad/85a30/diagrams/join-semi.png)
- Keep all observations in a dataset with a key in the other dataset
- Can be used instead of ```filter``` in some cases

In [21]:
# What are the top ten destinations?
top_dest <- flights %>%
    count(dest, sort = TRUE) %>%
    head(10) %>%
    print()

# A tibble: 10 x 2
   dest      n
   <chr> <int>
 1 ORD   17283
 2 ATL   17215
 3 LAX   16174
 4 BOS   15508
 5 MCO   14082
 6 CLT   14064
 7 SFO   13331
 8 FLL   12055
 9 MIA   11728
10 DCA    9705

In [22]:
# choose "dest" as the key
# keep all flights that have a key in the top_dest dataset
semi_join(flights, top_dest, by = "dest")

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   542      540             2         923      850
2      2013 1     1   554      600            -6         812      837
3      2013 1     1   554      558            -4         740      728
4      2013 1     1   555      600            -5         913      854
5      2013 1     1   557      600            -3         838      846
6      2013 1     1   558      600            -2         753      745
7      2013 1     1   558      600            -2         924      917
8      2013 1     1   558      600            -2         923      937
9      2013 1     1   559      559             0         702      706
10     2013 1     1   600      600             0         851      858
11     2013 1     1   600      600             0         837      825
12     2013 1     1   606      610            -4         858      910
13     2013 1     1   606      610            -4         837      845
14     2013 1     1   607      607             0         858      915
15     2013 1     1   608      600             8         807      735
16     2013 1     1   611      600            11         945      931
17     2013 1     1   615      615             0         833      842
18     2013 1     1   623      610            13         920      915
19     2013 1     1   628      630            -2        1016      947
20     2013 1     1   629      630            -1         824      810
21     2013 1     1   629      630            -1         824      833
22     2013 1     1   637      645            -8         930      935
23     2013 1     1   639      640            -1         739      749
24     2013 1     1   643      645            -2         837      848
25     2013 1     1   644      636             8         931      940
26     2013 1     1   655      700            -5        1037     1045
27     2013 1     1   655      700            -5        1002     1020
28     2013 1     1   656      700            -4         854      850
29     2013 1     1   656      659            -3         949      959
30     2013 1     1   657      700            -3         959     1013
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
141116 2013 9     30  2017     2022            -5       2132     2155
141117 2013 9     30  2017     2017             0       2253     2320
141118 2013 9     30  2022     2025            -3       2127     2140
141119 2013 9     30  2023     2025            -2       2315     2350
141120 2013 9     30  2026     2028            -2       2317     2340
141121 2013 9     30  2028     1910            78       2255     2215
141122 2013 9     30  2030     2045           -15       2141     2153
141123 2013 9     30  2030     2035            -5       2324     2340
141124 2013 9     30  2032     2045           -13       2147     2225
141125 2013 9     30  2035     2035             0       2142     2211
141126 2013 9     30  2041     2045            -4       2147     2208
141127 2013 9     30  2048     2100           -12       2147     2214
141128 2013 9     30  2050     2100           -10       2312     2344
141129 2013 9     30  2051     2054            -3       2348     2359
141130 2013 9     30  2052     2059            -7       2315     2358
141131 2013 9     30  2053     1815           158       2310     2054
141132 2013 9     30  2054     2100            -6       2240     2245
141133 2013 9     30  2055     2059            -4       2158     2211
141134 2013 9     30  2057     2100            -3       2149     2211
141135 2013 9     30  2121     2100            21       2349       14
141136 2013 9     30  2122     2127            -5       2226     2237
141137 2013 9     30  2127     2129            -2       2314     2323
141138 2013 9     30  2131     2140            -9       2225     2255
141139 2013 9     30  2140     2140             0         10       40
141140 2013 9     30  2147     2137            10         30       27
141141 2013 9     30  2149     2156            -7       2245     2308
141142 2013 9     30  2233     2113            80        112       30
141143 2013 9     30  2235     2001           154         59     2249
141144 2013 9     30  2307     2255            12       2359     2358
141145 2013 9     30    NA     1455            NA         NA     1634
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       33       AA      1141   N619AA  JFK    MIA  160      1089     5
2      -25       DL       461   N668DN  LGA    ATL  116       762     6
3       12       UA      1696   N39463  EWR    ORD  150       719     5
4       19       B6       507   N516JB  EWR    FLL  158      1065     6
5       -8       B6        79   N593JB  JFK    MCO  140       944     6
6        8       AA       301   N3ALAA  LGA    ORD  138       733     6
7        7       UA       194   N29129  JFK    LAX  345      2475     6
8      -14       UA      1124   N53441  EWR    SFO  361      2565     6
9       -4       B6      1806   N708JB  JFK    BOS   44       187     5
10      -7       B6       371   N595JB  LGA    FLL  152      1076     6
11      12       MQ      4650   N542MQ  LGA    ATL  134       762     6
12     -12       AA      1895   N633AA  EWR    MIA  152      1085     6
13      -8       DL      1743   N3739P  JFK    ATL  128       760     6
14     -17       UA      1077   N53442  EWR    MIA  157      1085     6
15      32       MQ      3768   N9EAMQ  EWR    ORD  139       719     6
16      14       UA       303   N532UA  JFK    SFO  366      2586     6
17      -9       DL       575   N326NB  EWR    ATL  120       746     6
18       5       AA      1837   N3EMAA  LGA    MIA  153      1096     6
19      29       UA      1665   N33289  EWR    LAX  366      2454     6
20      14       AA       303   N3CYAA  LGA    ORD  140       733     6
21      -9       US      1019   N426US  EWR    CLT   91       529     6
22      -5       B6       389   N709JB  LGA    MCO  144       950     6
23     -10       B6      1002   N805JB  JFK    BOS   41       187     6
24     -11       US       926   N178US  EWR    CLT   91       529     6
25      -9       UA      1701   N75435  EWR    FLL  151      1065     6
26      -8       DL      1865   N705TW  JFK    SFO  362      2586     7
27     -18       DL      2003   N997DL  LGA    MIA  161      1096     7
28       4       AA       305   N4WNAA  LGA    ORD  143       733     7
29     -10       AA      1815   N5FMAA  JFK    MCO  142       944     6
30     -14       DL      1879   N318NB  LGA    FLL  164      1076     7
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
141116 -23       B6       105   N298JB  JFK    ORD  112       740     20
141117 -27       UA       771   N510UA  JFK    LAX  304      2475     20
141118 -13       AA      2314   N3CUAA  JFK    BOS   37       187     20
141119 -35       B6       915   N712JB  JFK    SFO  327      2586     20
141120 -23       UA      1680   N31412  EWR    MIA  141      1085     20
141121  40       AA        21   N338AA  JFK    LAX  294      2475     19
141122 -12       B6      2680   N266JB  EWR    BOS   38       200     20
141123 -16       UA       374   N484UA  EWR    FLL  141      1065     20
141124 -38       AA       371   N434AA  LGA    ORD  105       733     20
141125 -29       9E      3395   N602LR  JFK    DCA   43       213     20
141126 -21       DL       985   N359NB  JFK    BOS   37       187     20
141127 -27       US      2197   N722US  LGA    DCA   39       214     21
141128 -32       B6       499   N606JB  LGA    MCO  122       950     21
141129 -11       B6       523   N605JB  JFK    LAX  304      2475     20
141130 -43       UA      1416   N68453  EWR    MCO  123       937     20
141131 136       EV      5292   N600QX  EWR    ATL   91       746     18
141132  -5       MQ      3384   N528MQ  LGA    CLT   70       544     21
141133 -13       UA      1066   N16701  EWR    BOS   40       200     20
141134 -22       US      2164   N953UW  LGA    BOS   35       184     21
141135 -25       DL      2363   N193DN  JFK    LAX  296      2475     21
141136 -11       EV      4372   N14902  EWR    DCA   35       199     21
141137  -9       EV      3833   N16546  EWR    CLT   72       529     21
141138 -30       MQ      3621   N807MQ  JFK    DCA   36       213     21
141139 -30       AA       185   N335AA  JFK    LAX  298      2475     21
141140   3       B6      1371   N627JB  LGA    FLL  139      1076     21
141141 -23       UA       523   N813UA  EWR    BOS   37       200     21
141142  42       UA       471   N578UA  EWR    SFO  318      2565     21
141143 130       B6      1083   N804JB  JFK    MCO  123       944     20
141144   1       B6       718   N565JB  JFK    BOS   33       187     22
141145  NA       9E      3393   NA      JFK    DCA   NA       213     14
       minute time_hour
1      40     2013-01-01 05:00:00
2       0     2013-01-01 06:00:00
3      58     2013-01-01 05:00:00
4       0     2013-01-01 06:00:00
5       0     2013-01-01 06:00:00
6       0     2013-01-01 06:00:00
7       0     2013-01-01 06:00:00
8       0     2013-01-01 06:00:00
9      59     2013-01-01 05:00:00
10      0     2013-01-01 06:00:00
11      0     2013-01-01 06:00:00
12     10     2013-01-01 06:00:00
13     10     2013-01-01 06:00:00
14      7     2013-01-01 06:00:00
15      0     2013-01-01 06:00:00
16      0     2013-01-01 06:00:00
17     15     2013-01-01 06:00:00
18     10     2013-01-01 06:00:00
19     30     2013-01-01 06:00:00
20     30     2013-01-01 06:00:00
21     30     2013-01-01 06:00:00
22     45     2013-01-01 06:00:00
23     40     2013-01-01 06:00:00
24     45     2013-01-01 06:00:00
25     36     2013-01-01 06:00:00
26      0     2013-01-01 07:00:00
27      0     2013-01-01 07:00:00
28      0     2013-01-01 07:00:00
29     59     2013-01-01 06:00:00
30      0     2013-01-01 07:00:00
⋮      ⋮      ⋮
141116 22     2013-09-30 20:00:00
141117 17     2013-09-30 20:00:00
141118 25     2013-09-30 20:00:00
141119 25     2013-09-30 20:00:00
141120 28     2013-09-30 20:00:00
141121 10     2013-09-30 19:00:00
141122 45     2013-09-30 20:00:00
141123 35     2013-09-30 20:00:00
141124 45     2013-09-30 20:00:00
141125 35     2013-09-30 20:00:00
141126 45     2013-09-30 20:00:00
141127  0     2013-09-30 21:00:00
141128  0     2013-09-30 21:00:00
141129 54     2013-09-30 20:00:00
141130 59     2013-09-30 20:00:00
141131 15     2013-09-30 18:00:00
141132  0     2013-09-30 21:00:00
141133 59     2013-09-30 20:00:00
141134  0     2013-09-30 21:00:00
141135  0     2013-09-30 21:00:00
141136 27     2013-09-30 21:00:00
141137 29     2013-09-30 21:00:00
141138 40     2013-09-30 21:00:00
141139 40     2013-09-30 21:00:00
141140 37     2013-09-30 21:00:00
141141 56     2013-09-30 21:00:00
141142 13     2013-09-30 21:00:00
141143  1     2013-09-30 20:00:00
141144 55     2013-09-30 22:00:00
141145 55     2013-09-30 14:00:00

### Anti-Join
![](https://d33wubrfki0l68.cloudfront.net/f29a85efd53a079cc84c14ba4ba6894e238c3759/c1408/diagrams/join-anti.png)
- Throw away all observations in a dataset with a key in the other dataset
- Useful in diagnosing problems

In [23]:
# flights w/ these year, month, day, hour tuples do not have a corresponding match in the weather dataset!
anti_join(flights, weather, by = c("year", "month", "day", "hour"))

     year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1    2013 10    25    13     2359            14        401      350
2    2013 10    25  1952     2000            -8       2129     2114
3    2013 10    25  1953     2000            -7       2241     2237
4    2013 10    25  1954     2000            -6       2101     2134
5    2013 10    25  1959     2001            -2       2229     2248
6    2013 10    25  2002     2000             2       2302     2328
7    2013 10    25  2005     2005             0       2122     2130
8    2013 10    25  2005     2000             5       2257     2315
9    2013 10    25  2011     2015            -4       2135     2144
10   2013 10    25  2013     2018            -5       2217     2202
11   2013 10    25  2015     2022            -7       2135     2155
12   2013 10    25  2016     2017            -1       2238     2320
13   2013 10    25  2016     2000            16       2243     2252
14   2013 10    25  2019     2009            10       2113     2129
15   2013 10    25  2019     2022            -3       2140     2200
16   2013 10    25  2020     2030           -10       2214     2201
17   2013 10    25  2020     2001            19       2252     2249
18   2013 10    25  2020     2015             5       2115     2125
19   2013 10    25  2022     2025            -3       2330     2350
20   2013 10    25  2025     2025             0       2231     2228
21   2013 10    25  2032     2018            14       2128     2144
22   2013 10    25  2037     2040            -3       2318     2258
23   2013 10    25  2039     2035             4       2330     2341
24   2013 10    25  2039     2025            14         19       26
25   2013 10    25  2039     2045            -6       2137     2153
26   2013 10    25  2042     2020            22       2324     2330
27   2013 10    25  2042     2045            -3       2219     2225
28   2013 10    25  2045     2000            45       2221     2132
29   2013 10    25  2046     2022            24       2257     2246
30   2013 10    25  2047     2030            17       2222     2205
⋮    ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
1264 2013 8     22  2203     2045            78       2354     2308
1265 2013 8     22  2204     2130            34         20     2359
1266 2013 8     22  2207     2100            67        102       12
1267 2013 8     22  2207     2049            78       2358     2304
1268 2013 8     22  2207     2159             8       2302     2319
1269 2013 8     22  2208     2035            93       2319     2201
1270 2013 8     22  2209     2029           100        108     2359
1271 2013 8     22  2212     2122            50       2315     2251
1272 2013 8     22  2216     2116            60       2339     2249
1273 2013 8     22  2217     2025           112         58     2321
1274 2013 8     22  2217     2119            58         35     2354
1275 2013 8     22  2217     2145            32       2336     2316
1276 2013 8     22  2222     2100            82       2321     2214
1277 2013 8     22  2222     2130            52       2320     2245
1278 2013 8     22  2225     2030           115         14     2245
1279 2013 8     22  2227     2105            82       2331     2230
1280 2013 8     22  2240     2140            60       2341     2259
1281 2013 8     22  2252     2030           142          8     2202
1282 2013 8     22  2258     2150            68          5     2311
1283 2013 8     22  2259     2000           179         57     2225
1284 2013 8     22  2259     2159            60          5     2324
1285 2013 8     22  2306     2125           101        107     2354
1286 2013 8     22  2313     2117           116        139        9
1287 2013 8     22  2316     2150            86        158      100
1288 2013 8     22  2324     2146            98        139       30
1289 2013 8     22  2327     2030           177         26     2155
1290 2013 8     22  2328     2059           149        101     2307
1291 2013 8     22  2329     2140           109         47     2310
1292 2013 8     22  2350     2100           170        203     2336
1293 2013 8     22    NA     2030            NA         NA     2211
     arr_delay carrier flight tailnum origin dest air_time distance hour minute
1     11       B6       745   N653JB  JFK    PSE  205      1617     23   59
2     15       US      2162   N946UW  LGA    BOS   38       184     20    0
3      4       DL      1147   N967DL  LGA    ATL  102       762     20    0
4    -33       9E      4127   N8672A  JFK    IAD   47       228     20    0
5    -19       B6        65   N517JB  JFK    ABQ  245      1826     20    1
6    -26       UA      1651   N37273  EWR    SFO  332      2565     20    0
7     -8       MQ      3604   N537MQ  EWR    ORD  115       719     20    5
8    -18       VX       415   N629VA  JFK    LAX  324      2475     20    0
9     -9       B6       702   N179JB  JFK    BUF   58       301     20   15
10    15       EV      5956   N14905  LGA    CLE   71       419     20   18
11   -20       B6       105   N193JB  JFK    ORD  119       740     20   22
12   -42       UA       771   N597UA  JFK    LAX  301      2475     20   17
13    -9       UA      1712   N24729  EWR    IAH  189      1400     20    0
14   -16       UA      1049   N77296  EWR    BOS   34       200     20    9
15   -20       UA      1464   N26215  EWR    CLE   61       404     20   22
16    13       FL       354   N920AT  LGA    CAK   62       397     20   30
17     3       B6      1083   N561JB  JFK    MCO  139       944     20    1
18   -10       B6       418   N595JB  JFK    BOS   35       187     20   15
19   -20       B6       915   N827JB  JFK    SFO  334      2586     20   25
20     3       EV      4348   N13914  EWR    MSP  163      1008     20   25
21   -16       9E      3885   N8913A  JFK    BWI   38       184     20   18
22    20       9E      4033   N831AY  LGA    TYS   92       647     20   40
23   -11       UA      1039   N37427  EWR    FLL  148      1065     20   35
24    -7       UA      1071   N34222  EWR    BQN  201      1585     20   25
25   -16       B6      2680   N328JB  EWR    BOS   43       200     20   45
26    -6       UA      1224   N45440  EWR    LAX  320      2454     20   20
27    -6       AA       371   N4YFAA  LGA    ORD  119       733     20   45
28    49       UA       695   N852UA  LGA    ORD  115       733     20    0
29    11       B6       135   N821JB  JFK    PHX  287      2153     20   22
30    17       WN       382   N246LV  LGA    MDW  114       725     20   30
⋮    ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
1264  46       9E      3367   N600LR  JFK    CVG   86       589     20   45
1265  21       B6      1677   N267JB  JFK    JAX  110       828     21   30
1266  50       DL      2065   N3735D  JFK    FLL  133      1069     21    0
1267  54       EV      4536   N12136  EWR    CVG   85       569     20   49
1268 -17       EV      4625   N12967  EWR    BWI   35       169     21   59
1269  78       9E      3748   N8976E  JFK    PHL   24        94     20   35
1270  69       B6       915   N637JB  JFK    SFO  330      2586     20   29
1271  24       UA      1146   N13248  EWR    BOS   44       200     21   22
1272  50       B6       702   N318JB  JFK    BUF   54       301     21   16
1273  97       B6      1295   N807JB  JFK    AUS  191      1521     20   25
1274  41       B6       527   N603JB  EWR    MCO  116       937     21   19
1275  20       DL       985   N331NB  JFK    BOS   41       187     21   45
1276  67       US      2197   N702UW  LGA    DCA   39       214     21    0
1277  35       MQ      3660   N506MQ  LGA    BNA  100       764     21   30
1278  89       9E      4033   N8884E  LGA    TYS   88       647     20   30
1279  61       MQ      3604   N8EGMQ  EWR    ORD  106       719     21    5
1280  42       EV      4372   N11551  EWR    DCA   36       199     21   40
1281 126       9E      4191   N8914A  JFK    BWI   33       184     20   30
1282  54       EV      4695   N14907  EWR    MHT   44       209     21   50
1283 152       MQ      3662   N5PBMQ  LGA    ATL  101       762     20    0
1284  41       UA      1142   N72405  EWR    BOS   43       200     21   59
1285  73       B6        97   N768JB  JFK    DEN  213      1626     21   25
1286  90       UA      1241   N27733  EWR    TPA  125       997     21   17
1287  58       AA       185   N328AA  JFK    LAX  309      2475     21   50
1288  69       B6      1183   N536JB  JFK    MCO  115       944     21   46
1289 151       WN      1707   N784SW  LGA    MDW  108       725     20   30
1290 114       EV      5254   N753EV  LGA    DSM  133      1031     20   59
1291  97       MQ      3317   N511MQ  LGA    RDU   64       431     21   40
1292 147       B6       499   N607JB  LGA    MCO  114       950     21    0
1293  NA       EV      5048   N713EV  LGA    RIC   NA       292     20   30
     time_hour
1    2013-10-25 23:00:00
2    2013-10-25 20:00:00
3    2013-10-25 20:00:00
4    2013-10-25 20:00:00
5    2013-10-25 20:00:00
6    2013-10-25 20:00:00
7    2013-10-25 20:00:00
8    2013-10-25 20:00:00
9    2013-10-25 20:00:00
10   2013-10-25 20:00:00
11   2013-10-25 20:00:00
12   2013-10-25 20:00:00
13   2013-10-25 20:00:00
14   2013-10-25 20:00:00
15   2013-10-25 20:00:00
16   2013-10-25 20:00:00
17   2013-10-25 20:00:00
18   2013-10-25 20:00:00
19   2013-10-25 20:00:00
20   2013-10-25 20:00:00
21   2013-10-25 20:00:00
22   2013-10-25 20:00:00
23   2013-10-25 20:00:00
24   2013-10-25 20:00:00
25   2013-10-25 20:00:00
26   2013-10-25 20:00:00
27   2013-10-25 20:00:00
28   2013-10-25 20:00:00
29   2013-10-25 20:00:00
30   2013-10-25 20:00:00
⋮    ⋮
1264 2013-08-22 20:00:00
1265 2013-08-22 21:00:00
1266 2013-08-22 21:00:00
1267 2013-08-22 20:00:00
1268 2013-08-22 21:00:00
1269 2013-08-22 20:00:00
1270 2013-08-22 20:00:00
1271 2013-08-22 21:00:00
1272 2013-08-22 21:00:00
1273 2013-08-22 20:00:00
1274 2013-08-22 21:00:00
1275 2013-08-22 21:00:00
1276 2013-08-22 21:00:00
1277 2013-08-22 21:00:00
1278 2013-08-22 20:00:00
1279 2013-08-22 21:00:00
1280 2013-08-22 21:00:00
1281 2013-08-22 20:00:00
1282 2013-08-22 21:00:00
1283 2013-08-22 20:00:00
1284 2013-08-22 21:00:00
1285 2013-08-22 21:00:00
1286 2013-08-22 21:00:00
1287 2013-08-22 21:00:00
1288 2013-08-22 21:00:00
1289 2013-08-22 20:00:00
1290 2013-08-22 20:00:00
1291 2013-08-22 21:00:00
1292 2013-08-22 21:00:00
1293 2013-08-22 20:00:00